/**:
    ros__parameters:
      video_device: "/dev/buggy_cam_left"
      framerate: 60.0
      io_method: "mmap"
      frame_id: "camera3/camera_optical_link"
      pixel_format: "mjpeg2rgb"  # see usb_cam/supported_formats for list of supported formats
      av_device_format: "YUV422P"
      image_width: 1280
      image_height: 720
      camera_name: "camera_left"
      camera_info_url: "file://$(find-pkg-share buggy_sensor_kit_launch)/config/camera_configuration/left_info.yaml"
      brightness: 0
      contrast: 0
      saturation: 0
      sharpness: 0
      gain: 0
      auto_white_balance: true
      white_balance: 4000
      autoexposure: true
      exposure: 100
      autofocus: false
      focus: 0