sensor_kit_base_link:
  camera_left/camera_link:
    x: -0.628
    y: 0.0125
    z: 1.47
    roll: 3.14159265
    pitch: 0.328
    yaw: 3.14159265
  camera1/camera_link:
    x: -0.10731
    y: -0.56343
    z: -0.27697
    roll: -0.025
    pitch: 0.32
    yaw: -2.12
  camera2/camera_link:
    x: -0.7
    y: 0.0125
    z: 1.52
    roll: 0.0
    pitch: 0.0
    yaw: 3.14159265
  traffic_light_right_camera/camera_link:
    x: 0.05
    y: -0.0175
    z: -0.1
    roll: 0.0
    pitch: 0.0
    yaw: 0.0
  traffic_light_left_camera/camera_link:
    x: 0.05
    y: 0.0175
    z: -0.1
    roll: 0.0
    pitch: 0.0
    yaw: 0.0
  velodyne_top_base_link:
    x: -0.454695
    y: -0.071382
    z: 1.602542
    roll: 0.000823
    pitch: -0.050952
    yaw: -3.093586

  velodyne_left_base_link:
    x: 3.149814
    y: 0.548026
    z: 0.597321
    roll: -0.016752
    pitch: -0.001892
    yaw: 0.029619

  velodyne_right_base_link:
    x: 3.198344
    y: -0.571953
    z: 0.580627
    roll: 0.016624
    pitch: 0.005591
    yaw: -0.028081
  gnss_link:
    x: 0.5
    y: 0.0
    z: 1.952
    roll: 0.0
    pitch: 0.0
    yaw: 0.0
  imu_link:
    x: -0.2
    y: 0.0
    z: 0.8
    roll: 0.0
    pitch: 0.0
    yaw: 0.0
